/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const IntentCategory = IDL.Variant({
  'ticket' : IDL.Null,
  'finance' : IDL.Null,
  'hotel' : IDL.Null,
  'food' : IDL.Null,
  'unknown' : IDL.Null,
});
export const CloudRecord = IDL.Record({
  'id' : IDL.Nat,
  'data' : IDL.Text,
  'taskId' : IDL.Nat,
  'syncedAt' : IDL.Int,
  'category' : IntentCategory,
});
export const BufferStatus = IDL.Variant({
  'flushing' : IDL.Null,
  'queued' : IDL.Null,
  'failed' : IDL.Null,
  'synced' : IDL.Null,
});
export const BufferItem = IDL.Record({
  'id' : IDL.Nat,
  'status' : BufferStatus,
  'queuedAt' : IDL.Int,
  'taskId' : IDL.Nat,
  'retryCount' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TaskStatus = IDL.Variant({
  'pending' : IDL.Null,
  'done' : IDL.Null,
  'processing' : IDL.Null,
  'failed' : IDL.Null,
});
export const AutomationTask = IDL.Record({
  'id' : IDL.Nat,
  'status' : TaskStatus,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'category' : IntentCategory,
  'payload' : IDL.Text,
});
export const Analytics = IDL.Record({
  'totalTasks' : IDL.Nat,
  'successRate' : IDL.Nat,
  'totalMessages' : IDL.Nat,
  'bufferSize' : IDL.Nat,
  'tasksByCategory' : IDL.Record({
    'ticket' : IDL.Nat,
    'finance' : IDL.Nat,
    'hotel' : IDL.Nat,
    'food' : IDL.Nat,
  }),
  'syncedCount' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ChatMessage = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'userId' : IDL.Principal,
  'intent' : IntentCategory,
  'timestamp' : IDL.Int,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCloudRecord' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [CloudRecord], []),
  'addToBuffer' : IDL.Func([IDL.Nat], [BufferItem], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createTask' : IDL.Func([IDL.Text, IDL.Text], [AutomationTask], []),
  'flushBuffer' : IDL.Func([], [IDL.Nat], []),
  'getAnalytics' : IDL.Func([], [Analytics], ['query']),
  'getBufferQueue' : IDL.Func([], [IDL.Vec(BufferItem)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCloudRecords' : IDL.Func([], [IDL.Vec(CloudRecord)], ['query']),
  'getMessages' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
  'getTasks' : IDL.Func([], [IDL.Vec(AutomationTask)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'pingExternalService' : IDL.Func([IDL.Text], [IDL.Text], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([IDL.Text], [ChatMessage], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateTaskStatus' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const IntentCategory = IDL.Variant({
    'ticket' : IDL.Null,
    'finance' : IDL.Null,
    'hotel' : IDL.Null,
    'food' : IDL.Null,
    'unknown' : IDL.Null,
  });
  const CloudRecord = IDL.Record({
    'id' : IDL.Nat,
    'data' : IDL.Text,
    'taskId' : IDL.Nat,
    'syncedAt' : IDL.Int,
    'category' : IntentCategory,
  });
  const BufferStatus = IDL.Variant({
    'flushing' : IDL.Null,
    'queued' : IDL.Null,
    'failed' : IDL.Null,
    'synced' : IDL.Null,
  });
  const BufferItem = IDL.Record({
    'id' : IDL.Nat,
    'status' : BufferStatus,
    'queuedAt' : IDL.Int,
    'taskId' : IDL.Nat,
    'retryCount' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TaskStatus = IDL.Variant({
    'pending' : IDL.Null,
    'done' : IDL.Null,
    'processing' : IDL.Null,
    'failed' : IDL.Null,
  });
  const AutomationTask = IDL.Record({
    'id' : IDL.Nat,
    'status' : TaskStatus,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'category' : IntentCategory,
    'payload' : IDL.Text,
  });
  const Analytics = IDL.Record({
    'totalTasks' : IDL.Nat,
    'successRate' : IDL.Nat,
    'totalMessages' : IDL.Nat,
    'bufferSize' : IDL.Nat,
    'tasksByCategory' : IDL.Record({
      'ticket' : IDL.Nat,
      'finance' : IDL.Nat,
      'hotel' : IDL.Nat,
      'food' : IDL.Nat,
    }),
    'syncedCount' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ChatMessage = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'userId' : IDL.Principal,
    'intent' : IntentCategory,
    'timestamp' : IDL.Int,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCloudRecord' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text],
        [CloudRecord],
        [],
      ),
    'addToBuffer' : IDL.Func([IDL.Nat], [BufferItem], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createTask' : IDL.Func([IDL.Text, IDL.Text], [AutomationTask], []),
    'flushBuffer' : IDL.Func([], [IDL.Nat], []),
    'getAnalytics' : IDL.Func([], [Analytics], ['query']),
    'getBufferQueue' : IDL.Func([], [IDL.Vec(BufferItem)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCloudRecords' : IDL.Func([], [IDL.Vec(CloudRecord)], ['query']),
    'getMessages' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
    'getTasks' : IDL.Func([], [IDL.Vec(AutomationTask)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'pingExternalService' : IDL.Func([IDL.Text], [IDL.Text], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([IDL.Text], [ChatMessage], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateTaskStatus' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };
