/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface CloudRecord {
    id: bigint;
    data: string;
    taskId: bigint;
    syncedAt: bigint;
    category: IntentCategory;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface http_header {
    value: string;
    name: string;
}
export interface BufferItem {
    id: bigint;
    status: BufferStatus;
    queuedAt: bigint;
    taskId: bigint;
    retryCount: bigint;
}
export interface Analytics {
    totalTasks: bigint;
    successRate: bigint;
    totalMessages: bigint;
    bufferSize: bigint;
    tasksByCategory: {
        ticket: bigint;
        finance: bigint;
        hotel: bigint;
        food: bigint;
    };
    syncedCount: bigint;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface AutomationTask {
    id: bigint;
    status: TaskStatus;
    userId: Principal;
    createdAt: bigint;
    category: IntentCategory;
    payload: string;
}
export interface ChatMessage {
    id: bigint;
    content: string;
    userId: Principal;
    intent: IntentCategory;
    timestamp: bigint;
}
export interface UserProfile {
    name: string;
}
export enum BufferStatus {
    flushing = "flushing",
    queued = "queued",
    failed = "failed",
    synced = "synced"
}
export enum IntentCategory {
    ticket = "ticket",
    finance = "finance",
    hotel = "hotel",
    food = "food",
    unknown_ = "unknown"
}
export enum TaskStatus {
    pending = "pending",
    done = "done",
    processing = "processing",
    failed = "failed"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addCloudRecord(taskId: bigint, data: string, category: string): Promise<CloudRecord>;
    addToBuffer(taskId: bigint): Promise<BufferItem>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createTask(category: string, payload: string): Promise<AutomationTask>;
    flushBuffer(): Promise<bigint>;
    getAnalytics(): Promise<Analytics>;
    getBufferQueue(): Promise<Array<BufferItem>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCloudRecords(): Promise<Array<CloudRecord>>;
    getMessages(): Promise<Array<ChatMessage>>;
    getTasks(): Promise<Array<AutomationTask>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    pingExternalService(url: string): Promise<string>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    sendMessage(content: string): Promise<ChatMessage>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateTaskStatus(taskId: bigint, status: string): Promise<boolean>;
}
import type { AutomationTask as _AutomationTask, BufferItem as _BufferItem, BufferStatus as _BufferStatus, ChatMessage as _ChatMessage, CloudRecord as _CloudRecord, IntentCategory as _IntentCategory, TaskStatus as _TaskStatus, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCloudRecord(arg0: bigint, arg1: string, arg2: string): Promise<CloudRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.addCloudRecord(arg0, arg1, arg2);
                return from_candid_CloudRecord_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCloudRecord(arg0, arg1, arg2);
            return from_candid_CloudRecord_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async addToBuffer(arg0: bigint): Promise<BufferItem> {
        if (this.processError) {
            try {
                const result = await this.actor.addToBuffer(arg0);
                return from_candid_BufferItem_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToBuffer(arg0);
            return from_candid_BufferItem_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createTask(arg0: string, arg1: string): Promise<AutomationTask> {
        if (this.processError) {
            try {
                const result = await this.actor.createTask(arg0, arg1);
                return from_candid_AutomationTask_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTask(arg0, arg1);
            return from_candid_AutomationTask_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async flushBuffer(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.flushBuffer();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.flushBuffer();
            return result;
        }
    }
    async getAnalytics(): Promise<Analytics> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalytics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalytics();
            return result;
        }
    }
    async getBufferQueue(): Promise<Array<BufferItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBufferQueue();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBufferQueue();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCloudRecords(): Promise<Array<CloudRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCloudRecords();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCloudRecords();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMessages(): Promise<Array<ChatMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessages();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessages();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTasks(): Promise<Array<AutomationTask>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTasks();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTasks();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async pingExternalService(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.pingExternalService(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.pingExternalService(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async sendMessage(arg0: string): Promise<ChatMessage> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0);
                return from_candid_ChatMessage_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0);
            return from_candid_ChatMessage_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateTaskStatus(arg0: bigint, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTaskStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTaskStatus(arg0, arg1);
            return result;
        }
    }
}
function from_candid_AutomationTask_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AutomationTask): AutomationTask {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_BufferItem_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BufferItem): BufferItem {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_BufferStatus_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BufferStatus): BufferStatus {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_ChatMessage_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChatMessage): ChatMessage {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_CloudRecord_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CloudRecord): CloudRecord {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_IntentCategory_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IntentCategory): IntentCategory {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_TaskStatus_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskStatus): TaskStatus {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _TaskStatus;
    userId: Principal;
    createdAt: bigint;
    category: _IntentCategory;
    payload: string;
}): {
    id: bigint;
    status: TaskStatus;
    userId: Principal;
    createdAt: bigint;
    category: IntentCategory;
    payload: string;
} {
    return {
        id: value.id,
        status: from_candid_TaskStatus_n13(_uploadFile, _downloadFile, value.status),
        userId: value.userId,
        createdAt: value.createdAt,
        category: from_candid_IntentCategory_n3(_uploadFile, _downloadFile, value.category),
        payload: value.payload
    };
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    data: string;
    taskId: bigint;
    syncedAt: bigint;
    category: _IntentCategory;
}): {
    id: bigint;
    data: string;
    taskId: bigint;
    syncedAt: bigint;
    category: IntentCategory;
} {
    return {
        id: value.id,
        data: value.data,
        taskId: value.taskId,
        syncedAt: value.syncedAt,
        category: from_candid_IntentCategory_n3(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    content: string;
    userId: Principal;
    intent: _IntentCategory;
    timestamp: bigint;
}): {
    id: bigint;
    content: string;
    userId: Principal;
    intent: IntentCategory;
    timestamp: bigint;
} {
    return {
        id: value.id,
        content: value.content,
        userId: value.userId,
        intent: from_candid_IntentCategory_n3(_uploadFile, _downloadFile, value.intent),
        timestamp: value.timestamp
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _BufferStatus;
    queuedAt: bigint;
    taskId: bigint;
    retryCount: bigint;
}): {
    id: bigint;
    status: BufferStatus;
    queuedAt: bigint;
    taskId: bigint;
    retryCount: bigint;
} {
    return {
        id: value.id,
        status: from_candid_BufferStatus_n7(_uploadFile, _downloadFile, value.status),
        queuedAt: value.queuedAt,
        taskId: value.taskId,
        retryCount: value.retryCount
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    done: null;
} | {
    processing: null;
} | {
    failed: null;
}): TaskStatus {
    return "pending" in value ? TaskStatus.pending : "done" in value ? TaskStatus.done : "processing" in value ? TaskStatus.processing : "failed" in value ? TaskStatus.failed : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ticket: null;
} | {
    finance: null;
} | {
    hotel: null;
} | {
    food: null;
} | {
    unknown: null;
}): IntentCategory {
    return "ticket" in value ? IntentCategory.ticket : "finance" in value ? IntentCategory.finance : "hotel" in value ? IntentCategory.hotel : "food" in value ? IntentCategory.food : "unknown" in value ? IntentCategory.unknown : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    flushing: null;
} | {
    queued: null;
} | {
    failed: null;
} | {
    synced: null;
}): BufferStatus {
    return "flushing" in value ? BufferStatus.flushing : "queued" in value ? BufferStatus.queued : "failed" in value ? BufferStatus.failed : "synced" in value ? BufferStatus.synced : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BufferItem>): Array<BufferItem> {
    return value.map((x)=>from_candid_BufferItem_n5(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CloudRecord>): Array<CloudRecord> {
    return value.map((x)=>from_candid_CloudRecord_n1(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ChatMessage>): Array<ChatMessage> {
    return value.map((x)=>from_candid_ChatMessage_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AutomationTask>): Array<AutomationTask> {
    return value.map((x)=>from_candid_AutomationTask_n11(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
