/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Analytics {
  'totalTasks' : bigint,
  'successRate' : bigint,
  'totalMessages' : bigint,
  'bufferSize' : bigint,
  'tasksByCategory' : {
    'ticket' : bigint,
    'finance' : bigint,
    'hotel' : bigint,
    'food' : bigint,
  },
  'syncedCount' : bigint,
}
export interface AutomationTask {
  'id' : bigint,
  'status' : TaskStatus,
  'userId' : Principal,
  'createdAt' : bigint,
  'category' : IntentCategory,
  'payload' : string,
}
export interface BufferItem {
  'id' : bigint,
  'status' : BufferStatus,
  'queuedAt' : bigint,
  'taskId' : bigint,
  'retryCount' : bigint,
}
export type BufferStatus = { 'flushing' : null } |
  { 'queued' : null } |
  { 'failed' : null } |
  { 'synced' : null };
export interface ChatMessage {
  'id' : bigint,
  'content' : string,
  'userId' : Principal,
  'intent' : IntentCategory,
  'timestamp' : bigint,
}
export interface CloudRecord {
  'id' : bigint,
  'data' : string,
  'taskId' : bigint,
  'syncedAt' : bigint,
  'category' : IntentCategory,
}
export type IntentCategory = { 'ticket' : null } |
  { 'finance' : null } |
  { 'hotel' : null } |
  { 'food' : null } |
  { 'unknown' : null };
export type TaskStatus = { 'pending' : null } |
  { 'done' : null } |
  { 'processing' : null } |
  { 'failed' : null };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCloudRecord' : ActorMethod<[bigint, string, string], CloudRecord>,
  'addToBuffer' : ActorMethod<[bigint], BufferItem>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createTask' : ActorMethod<[string, string], AutomationTask>,
  'flushBuffer' : ActorMethod<[], bigint>,
  'getAnalytics' : ActorMethod<[], Analytics>,
  'getBufferQueue' : ActorMethod<[], Array<BufferItem>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCloudRecords' : ActorMethod<[], Array<CloudRecord>>,
  'getMessages' : ActorMethod<[], Array<ChatMessage>>,
  'getTasks' : ActorMethod<[], Array<AutomationTask>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'pingExternalService' : ActorMethod<[string], string>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[string], ChatMessage>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateTaskStatus' : ActorMethod<[bigint, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
